### ISSUE TITLE
Add CodeTrans, a model for source code generation, documentation generation and similar subtasks.

### ISSUE THREAD

**Issue by tanmaylaud** [huggingface/transformers#11114]
# 🌟 New model addition

 Paper: https://arxiv.org/abs/2104.02443

## Open source status

* [ ] the model implementation is available: https://github.com/agemagician/CodeTrans
* [ ] the model weights are available:
https://github.com/agemagician/CodeTrans
Currently tensorflow.
* [ ] who are the authors: @agemagician

**Comment by agemagician** [comment]
Hi @tanmaylaud ,

Thanks for creating this issue and your interest.

We already integrated our models into hugging face :)
You can find all of them here:
[https://huggingface.co/models?search=code_trans_](https://huggingface.co/models?search=code_trans_)

@patrickvonplaten : FYI, we have released the paper and all the models. All the models are fully integrated into hugging face library.

**Comment by tanmaylaud** [comment]
@agemagician Sorry, I didn't notice it may be because of the search terms I used. 
Thanks ! 
I think it deserves a separate category instead of 'Summarization'.

**Comment by LysandreJik** [comment]
Closed by @agemagician  :)
