### ISSUE TITLE
Add more model resources

### ISSUE THREAD

**Issue by stevhliu** [huggingface/transformers#19848]
A continuation of #19767 to add existing official resources (blog posts, notebooks, scripts, etc.) directly to the model docs for 20 of the most popular architectures based on last month's pageviews. I'm not sure whether there are existing resources for all of these models, but I'll check it out, and if not we can either:

* Move to the next most popular model
* Or it could be a good opportunity to create some resources for it

Tracking model progress and updates:

- [x] BERT (see #19852)
- [x] T5 (see #19878)
- [x] RoBERTa (see #19911)
- [x] GPT2 (see #19879)
- [x] BLOOM (see #19881)
- [x] BART (see #19928)
- [x] ViT (assigned to @stanleycai95)
- [x] DistilBERT (see #19930)
- [x] Wav2Vec2 (see #19931)
- [x] LayoutLMV3 (see #19932)
- [x] CLIP (assigned to @ambujpawar, see #20190)
- [x] LayoutLM (assigned to @avisinghal6)
- [x] GPT-J (assigned to @adit299)
- [x] TrOCR (assigned to @huangperry)
- [x] LayoutLMV2 (assigned to @y3sar)
- [x] ALBERT (assigned to @ENate)
- [x] OPT (assigned to @alissadb)
- [x] DeBERTa (assigned to @Saad135, see #20155)
- [x] OpenAI GPT (assigned to @shogohida, see #20084)
- [x] XLM-RoBERTa (assigned to @hazrulakmal)

**Comment by sayakpaul** [comment]
@stevhliu @NielsRogge is there a plan to add the additional vision tasks we currently support to [this page](https://huggingface.co/docs/transformers/task_summary#image-classification)? For example object detection, segmentation, video classification. Then there seems to be an entire section missing on multimodal models. 

I understand for these tasks, we don't have `pipeline`s yet. But I believe we can still enlist these tasks with our existing resources (notebooks, blog posts, scripts, etc.).

Another suggestion is to provide consolidated model links for each of the tasks enlisted in that page. For example, for image classification, it could be https://huggingface.co/models?pipeline_tag=image-classification. 

WDYT? 

Cc: @osanseviero @nateraw

**Comment by NielsRogge** [comment]
> @stevhliu @NielsRogge is there a plan to add the additional vision tasks we currently support to [this page](https://huggingface.co/docs/transformers/task_summary#image-classification)?

Yes I've pinged @stevhliu yesterday about this ;) he's working on it

**Comment by sayakpaul** [comment]
Amazing! @stevhliu, if possible could tag me in the PR when you open it? Would love to take a look.

**Comment by stanleycai95** [comment]
Hi! Could I try ViT?

**Comment by avisinghal6** [comment]
Hi, I am a newbie to open source and would like to contribute. @NielsRogge can I contribute to this issue?

**Comment by stevhliu** [comment]
Welcome @avisinghal6, we'd be more than happy for you to make a contribution! 🤗 

The remaining models available are LayoutLM, LayoutLMV2, TrOCR, and OPT. Let me know which model you'd like to take on, and any questions you might have!

**Comment by avisinghal6** [comment]
@stevhliu, I can start working on LayoutLM model. So I need to search for existing official resources on hugging face website and attach relevant ones to the documentation of LayoutLM model ?

**Comment by stevhliu** [comment]
Yup, check out issue #20055 for a list of resources to search from and the [BERT resources section](https://huggingface.co/docs/transformers/model_doc/bert#resources) for an example of what it should look like!

**Comment by avisinghal6** [comment]
@stevhliu, I have added the resources for LayoutLM. Commit : d360021d9caef517854e371f8ac286f1c0a4f802

**Comment by stevhliu** [comment]
Hi @avisinghal6, would you mind opening a pull request on the Transformers repository for your contribution? You can check out this [guide](https://www.notion.so/huggingface2/Contribution-Guide-19411c29298644df8e9656af45a7686d#ed2eea8d355c497d9f05474e349f9f15) for more details how. Thanks! 😄

**Comment by avisinghal6** [comment]
Hi @stevhliu, I have created the PR#21377

**Comment by SarangShrivastava** [comment]
Hi @stevhliu - I want to add resources for LayoutLMv2. Will submit a PR soon.

**Comment by stevhliu** [comment]
Looking forward to your contribution @SarangShrivastava!

**Comment by rajveer43** [comment]
hey, @stevhliu I want to work on any of the model if its available

**Comment by stevhliu** [comment]
Hey @SarangShrivastava , just checking to see if you're still interested in making a model contribution. Totally cool if you aren't available anymore, I'll unassign you from the model you claimed and let someone else take a stab at it. Thanks!

@rajveer43 thanks for your interest! If any of the models free up, I'll let you know 🤗

**Comment by y3sar** [comment]
Hello @stevhliu I would like to make my first contribution to transformers and this looks like a great place to start😄. Is there any way I can help? I can see all the models have been assigned is it possible to work on a model already assigned? Thanks in advance

**Comment by stevhliu** [comment]
Thanks for the interest; TrOCR, LayoutLMV2, and ALBERT are now available!

**Comment by y3sar** [comment]
@stevhliu I would like to start working on LayoutLMV2.

**Comment by y3sar** [comment]
@stevhliu I have a question regarding 🌎 emoji. Exactly which resources should be marked by it?

**Comment by stevhliu** [comment]
🌎 is for unofficial Hugging Face resources, such as community-created ones. For example, if you look at the GPT2 [resources](https://huggingface.co/docs/transformers/v4.28.1/en/model_doc/gpt2#resources), there are links to notebooks for generating lyrics and tweets from contributors :)

**Comment by y3sar** [comment]
@stevhliu thanks for the response. I noticed in BERT resources under text-classification a notebook by NielsRogge is not marked 🌎. Are[these notebooks](https://github.com/NielsRogge/Transformers-Tutorials/tree/master/LayoutLMv2) considered official?

**Comment by unitinguncle** [comment]
Hello @stevhliu I would like to make my first contribution to open source transformers and this looks like a great place to start. Is there any way I can help? Thanks in advance

**Comment by stevhliu** [comment]
Hi, thanks for your interest @unitinguncle! Currently, all the models are taken but I'll let you know if something is available. In the meantime, feel free to also take a look at some of the [Good First Issue's](https://github.com/huggingface/transformers/issues?q=is%3Aopen+is%3Aissue+label%3A%22Good+First+Issue%22) to see if there is anything else you may be interested in!

**Comment by raj-pandey55** [comment]
Hello @stevhliu I would like to make my first contribution to transformers and this looks like a great place to start😄. Is there any way I can make a contribution here? Thanks in advance

**Comment by stevhliu** [comment]
Thanks for your interest @raj-pandey55! It looks like ALBERT is the only model left to complete. @ENate, are you still interested in making a contribution? If not, I'll reassign it to @raj-pandey55 🙂

**Comment by raj-pandey55** [comment]
Thanks for letting me know @ENate . @stevhliu if any new opportunity comes up, please let me know🤗. Thanks in advance

**Comment by divyam-prajapati** [comment]
Hi there! 👋

Hello @stevhliu, I'm new to open source contributions, and I'm excited to start my journey by helping out here. I'm eager to learn and collaborate with the community. If there are any specific areas in the documentation that need attention, please let me know, and I'd be happy to take them on.
