### ISSUE TITLE
[i18n-JP] Translating `en/model_doc` docs to Japanese

### ISSUE THREAD

**Issue by rajveer43** [huggingface/transformers#27392]
Hi!

Let's bring the documentation to all the Japanese-speaking community 🌐 

Who would want to translate? Please follow the 🤗 [TRANSLATING guide](https://github.com/huggingface/transformers/blob/main/docs/TRANSLATING.md). Here is a list of the files ready for translation. Let us know in this issue if you'd like to translate any, and we'll add your name to the list.

Some notes:

* Please translate using an informal tone (imagine you are talking with a friend about transformers 🤗).
* Please translate in a gender-neutral way.
* Add your translations to the folder called `ja` inside the [source folder](https://github.com/huggingface/transformers/tree/main/docs/source).
* Register your translation in `ja/_toctree.yml`; please follow the order of the [English version](https://github.com/huggingface/transformers/blob/main/docs/source/en/_toctree.yml).
* Once you're finished, open a pull request and tag this issue by including #issue-number in the description, where issue-number is the number of this issue. Please ping @stevhliu and @MKhalusova for review.
* 🙋 If you'd like others to help you with the translation, you can also post in the 🤗 [forums](https://discuss.huggingface.co/).

## Model_doc section
- [x] [albert.md](https://github.com/huggingface/transformers/blob/main/docs/source/en/model_doc/albert.md) #27401
- [x]  [align.md.md](https://github.com/huggingface/transformers/blob/main/docs/source/en/model_doc/align.md) #27401
- [x]  [altclip.md](https://github.com/huggingface/transformers/blob/main/docs/source/en/model_doc/altclip.md) #27401
- [x]  [audio-spectrogram-transformer.md](https://github.com/huggingface/transformers/blob/main/docs/source/en/model_doc/audio-spectrogram-transformer.md) #27401
- [x]  [auto.md](https://github.com/huggingface/transformers/blob/main/docs/source/en/model_doc/auto.md) #27401
- [x]  [autoformer.md](https://github.com/huggingface/transformers/blob/main/docs/source/en/model_doc/autoformer.md) #27401
- [x]  [bark.md](https://github.com/huggingface/transformers/blob/main/docs/source/en/model_doc/bark.md) #27264
- [x]  [bart.md](https://github.com/huggingface/transformers/blob/main/docs/source/en/model_doc/bart.md) #27264
- [x]  [barthez.md](https://github.com/huggingface/transformers/blob/main/docs/source/en/model_doc/barthez.md) #27264
- [x]  [bartpho.md](https://github.com/huggingface/transformers/blob/main/docs/source/en/model_doc/bartpho.md) #27264
- [x]  [beit.md](https://github.com/huggingface/transformers/blob/main/docs/source/en/model_doc/beit.md) #27264
- [x]  [bert-generation.md](https://github.com/huggingface/transformers/blob/main/docs/source/en/model_doc/bert-generation.md) #27264
- [x]  [bert-japanese.md](https://github.com/huggingface/transformers/blob/main/docs/source/en/model_doc/bert-japanese.md) #27264
- [x]  [bert.md](https://github.com/huggingface/transformers/blob/main/docs/source/en/model_doc/bert.md) [](#27264)
- [x]  [bertweet.md](https://github.com/huggingface/transformers/blob/main/docs/source/en/model_doc/bertweet.md) #27264
- [x]  [big_bird.md](https://github.com/huggingface/transformers/blob/main/docs/source/en/model_doc/big_bird.md) #27401
- [x]  [bigbird_pegasus.md](https://github.com/huggingface/transformers/blob/main/docs/source/en/model_doc/bigbird_pegasus.md) #27264
- [ ]  [biogpt.md](https://github.com/huggingface/transformers/blob/main/docs/source/en/model_doc/biogpt.md) #27264
- [ ]  [bit.md](https://github.com/huggingface/transformers/blob/main/docs/source/en/model_doc/bit.md) #27264
- [ ]  [blenderbot-small.md](https://github.com/huggingface/transformers/blob/main/docs/source/en/model_doc/blenderbot-small.md) #27264
- [ ]  [blenderbot.md](https://github.com/huggingface/transformers/blob/main/docs/source/en/model_doc/blenderbot.md) #27264

Keep on adding more as you go 🔥

**Comment by rajveer43** [comment]
> Thanks for the information!
> Just to be sure, would it be correct if I translate the rest of the `model_docs` that are not listed in the **Model_do section**?

@Yuki-Imajuku no, you can start from the listed files, they are yet to be translated! 10 docs/PR would work.

**Comment by Yuki-Imajuku** [comment]
Oh, I was right to ask for confirmation...... I got it! I'll try to work on them :)

**Comment by rajveer43** [comment]
> Oh, I was right to ask for confirmation...... I got it! I'll try to work on them :)

Just tick them off when you complete them.
