### ISSUE TITLE
[2D Parallelism] Tracking feasibility

### ISSUE THREAD

**Issue by stas00** [huggingface/transformers#9931]
The next stage in Parallelism and to be able to get bigger models onto smaller hardware is 2D Parallelism. That's combining Pipeline Parallelism (PP) with ZeRO-DP. Each 1D allows for a much more efficient utilization of the gpu memory, but it's still not enough for very big models - sometimes not even feasible with any of the existing hardware.

We have 3 implementations that provide these, so this issue is to track the feasibility/status/inter-operability in each one of them.

### 1. DeepSpeed

1D status:
* [x] PP
* [x] ZeRO-DP

2D native status:
* [ ] native PP + ZeRO-DP - untested yet, as it requires porting to native PP first 

2D inter-operability status:
- [:x:] I tried using pytorch PP with DeepSpeed ZeRO-DP and couldn't figure out how to make it work: https://github.com/microsoft/DeepSpeed/issues/710

Important components:
* MPU https://github.com/microsoft/DeepSpeedExamples/blob/master/Megatron-LM/mpu/initialize.py

 
### 2. FairScale

Just started gather information on this one - will update once I have it.

1D status:
* [x] PP
* [x] ZeRO-DP

2D native status:
* [ ] native PP + ZeRO-DP - gathering info

2D inter-operability status:
- [  ] gathering info

Important components:
* MPU https://github.com/facebookresearch/fairscale/blob/master/fairscale/nn/model_parallel/initialize.py#L41

### 3. PyTorch

pytorch has been integrating from what I understand primarily fairscale version into its core.

1D status:
* [x] PP - experimental support. have PoC t5 working: https://github.com/huggingface/transformers/pull/9765
* [ ] ZeRO-DP - plans to implement that (primarily integrating fairscale implementation)

2D native status:
native PP + ZeRO-DP 

2D inter-operability status:
- [:x:] pytorch PP + DeepSpeed ZeRO-DP I tried using pytorch PP with DeepSpeed ZeRO-DP and couldn't figure out how to make it work: https://github.com/microsoft/DeepSpeed/issues/710
- [:x:] pytorch PP + DeepSpeed ZeRO-DP

**Comment by LifeIsStrange** [comment]
Zero-3 has recently been announced
https://news.ycombinator.com/item?id=26447018#26448858
"ZeRO-3 Offload goes beyond the state-of-the-art hybrid 3D-parallelism (data, model and pipeline parallelism combined). While 3D Parallelism is limited by the aggregate GPU memory, ZeRO-3 Offload can exploit both GPU and CPU memory, the latter of which is much larger and cheaper compared to GPU memory. This allows ZeRO-3 Offload to train larger model sizes with the given GPU and CPU resources than any other currently available technology."

**Comment by stas00** [comment]
Thank you for the heads up, @LifeIsStrange 

This particular issue collects notes on something quite orthogonal to ZeRO-3, see https://github.com/huggingface/transformers/issues/9766 for a more suitable discussion.

And yes, we are working on integrating ZeRO3 from fairscale and Deepspeed into transformers. There are still some rough edges but hopefully it'll be ready really soon now.
